### ISSUE TITLE
New point release containing doc fix please.

### ISSUE THREAD

**Issue by ringods** [thulasirajkomminar/pulumi-influxdb#8]
Hello @thulasirajkomminar,

I'm from the Pulumi team. Would it be possible to create a new point release (e.g. 1.0.2) which contains the fix for this doc file?

https://github.com/komminarlabs/pulumi-influxdb/commit/c3ccec6defa19ff92de094035e82b7cb6d8688d7#diff-c842590019e88255dcb723f9dfdadc9185e22a2f4fc7010f1ec3c404759e5540

We currently have a 404 in our Registry on the incorrect link.

**Comment by thulasirajkomminar** [comment]
Hi @ringods 

Created a new release `v1.0.2`
